trigger: none
pr: none

#Specifies where jobs run (Microsoft-hosted or self-hosted agents). Here we used selfhosted agent.   
pool:
  name: 'Selfhosted'
  
steps: 
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'pranjit-playground-kvaccess-con'
    KeyVaultName: 'kv-pranjit-playground'
    SecretsFilter: 'pranjt-test-kv'
    RunAsPreJob: true
- script: echo "Secret value:$(pranjt-test-kv)"
  displayName: 'Display Secret'

- script: |
    echo "##vso[task.setvariable variable=plainSecret;issecret=false]$(pranjt-test-kv)"
    echo "Unmasked secret:$(plainSecret)"
  displayName: 'Unmasked Secret for Debugging'
