# CreateAzureResourceUsingAzureCLICommand.yaml
trigger:
- none
pool:
  name: 'Selfhosted'

parameters:  
  - name: environment
    type: string
    default: dev    
    values:
      - dev
      - test
      - prod  
    displayName: Select Environment
variables:
    selectedEnv: ${{ parameters.environment }}

steps:
- script: |
    echo "Running in environment: $(selectedEnv)"
  displayName: 'Print Selected Environment'
