trigger:
  branches:
    include:
      - main  # runs when you push to main branch

name: 'Replace Files in Existing LinuxVMSS'

steps:  
  - task: Checkout@1  # To checkout the current repo so that we can coly the folder from repo 
