trigger:
  - none

variables:
  resourceGroup: 'vmss-static-web-rg-208'
  vmssName: 'web-vmss'
  targetPath: '/var/www/html'  
  gitfolderpath: 'Resources/v2/'

name: 'Upload File to VMSS'

steps:
  - checkout: self

  - script: |
      echo "Packaging CSS file..."
      tar -czf folder.tar.gz ${{ variables.gitfolderpath }}
    displayName: "Compress updated CSS file"
      

 
