trigger:
  - none

variables:
  resourceGroup: 'vmss-static-web-rg-208'
  vmssName: 'web-vmss'
  targetPath: '/var/www/html'  
  gitfolderpath: 'Resources/v2/'

name: 'Upload File to VMSS'

steps:
  - checkout: self

  - script: |
      echo "Packaging CSS file..."
      tar -czf /tmp/folder.tar.gz ${{ variables.gitfolderpath }}
      echo "Checking if tar file was created..."
      ls -lh /tmp/folder.tar.gz

      # Convert to base64 string for transfer
      TAR_B64=$(base64 /tmp/folder.tar.gz)
      echo $TAR_B64 > /tmp/folder.b64
    displayName: "Compress updated CSS file"   
  
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'pranjit-playground(69869722-481a-4f0b-b1b2-800a599c43fd)'  # <-- your Azure service connection name
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        echo "Listing VMSS instances..."
        instances=$(az vmss list-instances --resource-group ${{ variables.resourceGroup }} --name ${{ variables.vmssName }} --query "[].instanceId" -o tsv)
        TAR_B64=$(base64 /tmp/folder.tar.gz) 
        for id in $instances; do
          echo "Updating instance: $id"
          az vmss run-command invoke \
            --command-id RunShellScript \
            --name ${{ variables.vmssName }} \
            --resource-group ${{ variables.resourceGroup }} \
            --instance-id $id \
            --scripts "
              mkdir -p /tmp/deploy
              cd /tmp/deploy
              echo 'Updating website...'
              rm -rf *
              echo $TAR_B64 | base64 -d > /tmp/deploy/folder.tar.gz
              tar -xzf /tmp/deploy/folder.tar.gz -C ${{ variables.targetPath }}
              systemctl restart nginx
              echo 'Deployment completed for instance $id'
            "
        done
    displayName: "Deploy updated CSS to all VMSS instances"
      

 
