trigger:
    - none

variables:
    TF_WORKING_DIR: "/teraform/azure-storage-account"

steps:
    - checkout: self

    # Step 1: Install Terraform CLI
    - task: TerraformInstaller@1
      inputs:
       terraformVersion: '1.5.7'

    # Step 2: Initialize Terraform
    - script: |
       cd $(TF_WORKING_DIR)
       terraform init
      displayName: 'Terraform Init'

    # Step 3: validate Terraform
    - script: |
       cd $(TF_WORKING_DIR)
       terraform validate
      displayName: 'Terraform validate'
      
    # Step 4: plan Terraform
    - script: |
       cd $(TF_WORKING_DIR)
       terraform plan -out=tfplan -var "subscription_id=$(AZURE_SUBSCRIPTION_ID)" -var "client_id=$(AZURE_CLIENT_ID)" -var "client_secret=$(AZURE_CLIENT_SECRET)" -var "tenant_id=$(AZURE_TENANT_ID)"
      displayName: 'Terraform plan'      

    # Step 5: Apply Terraform
    - script: |
       cd $(TF_WORKING_DIR)
       terraform apply -auto-approve tfplan
      displayName: 'Terraform Plan'      
    

