trigger:
    - none

variables:
    # Defile local variable 
    - name: 'TF_WORKING_DIR'
      value: "terraform/azure-appservice"    

    # Load shared secrets from Library Variable Group
    - group: TerraformSecrets

    # Load variable from another template
    - template: "common_variable.yaml"

name: "Appservice deployment"

stages:
    - stage: 'Provisioning'
      jobs:          
          - job: 'Teraform_Execute'
            displayName: 'Teraform_Execute'
            steps:
            # Step 1: Display All environment variables
             - script: |
                echo "=== All Environment Variables ==="
                printenv | sort
                displayName: "Show All Pipeline Variables"

            # Step 2: Install Terraform CLI
             - task: TerraformInstaller@1
               inputs:
                 terraformVersion: '1.5.7'

            # Step 2: Initialize Terraform
             - script: |
                cd $(TF_WORKING_DIR)
                terraform init
                displayName: 'Terraform Init'

            # Step 3: Terraform Validate
             - script: |
                cd $(TF_WORKING_DIR)
                terraform validate
                displayName: 'Terraform Validate'
                      # Step 4: Terraform Plan
             - script: |
                terraform -chdir=$(TF_WORKING_DIR) plan -out=tfplan -var "subscription_id=$(AZURE_SUBSCRIPTION_ID)" -var "client_id=$(AZURE_CLIENT_ID)" -var "client_secret=$(AZURE_CLIENT_SECRET)" -var "tenant_id=$(AZURE_TENANT_ID)" -var "build_id=$(build_id)"
                displayName: 'Terraform Plan'

          # Step 5: Terraform Apply
             - script: |
                cd $(TF_WORKING_DIR)
                terraform apply -auto-approve tfplan
                displayName: 'Terraform Apply'


